//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomWord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomWord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice fing an sich zu langweilen, sie sass schon lange bei ihrer Schwesteram Ufer und hatte nichts zu thun.
        ///Das Buch, das ihre Schwester las, gefielihr nicht, denn es waren weder Bilder noch Gespräche darin.
        ///Und wasnützen Bücher, dachte Alice, ohne Bilder und Gespräche?
        ///Sie überlegte sich eben, so gut es ging, denn sie war schläfrig und dummvon der Hitze, ob es der Mühe werth sei aufzustehen und Gänseblümchenzu pflücken, um eine Kette damit zu machen, als plötzlich ein weissesKaninchen mit rothen Augen d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _AllSentences_ {
            get {
                return ResourceManager.GetString("_AllSentences_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aa
        ///Aachen
        ///Aachener
        ///Aachens
        ///Aal
        ///Aalborg
        ///Aale
        ///aalen
        ///Aalen
        ///Aalener
        ///Aalfang
        ///Aalfischer
        ///aalglatt
        ///Aalhamen
        ///aalig
        ///Aalkorb
        ///Aalleiter
        ///Aalnetz
        ///Aalräucherei
        ///Aalreuse
        ///Aalspeer
        ///Aalstechen
        ///Aalstrich
        ///Aaltreppe
        ///Aalwanderung
        ///Aar
        ///Aarau
        ///Aare
        ///Aareal
        ///Aargau
        ///Aargauer
        ///aargauisch
        ///Aarhus
        ///Aaron
        ///Aas
        ///Aasbande
        ///aasen
        ///Aasfliege
        ///Aasfresser
        ///Aasgeier
        ///Aasgeruch
        ///Aasgestank
        ///aasig
        ///Aasinsekt
        ///Aasjäger
        ///Aaskäfer
        ///Aasvogel
        ///ab
        ///Ab
        ///Abakus
        ///abänderbar
        ///abändern
        ///Abänderung
        ///Abänderungsantrag
        ///abänderungsbe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _AllWords_ {
            get {
                return ResourceManager.GetString("_AllWords_", resourceCulture);
            }
        }
    }
}
